language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - COMPOSER_ROOT_VERSION=dev-master composer install

script:
  - phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
